repos:
  - repo: https://github.com/PyCQA/docformatter
    rev: v1.7.7
    hooks:
      - id: docformatter
        name: docformatter - format docstrings
        args: ["--in-place"]
        language: python
        default_python_version: python3